### ISSUE TITLE
As a develop I want the data in the chart to change in response to other actions on the page

### ISSUE THREAD

**Issue by dbouwman** [esridc/cedar#13]
Generalized from https://github.com/esridc/cedar/issues/12

> I zoomed the map to this area. While it is useful to use the popup to query parts of the map, 
> I really want the chart to instantly tell me something about the data using this map’s extent.
>
> Example: in Urban Observatory, I see three population density maps side by side, but I really want to 
> know how many people are represented, in total, for each map’s extent 

### Pseudo code
```
//assumes we have a map object
var self = this;
Cedar.show(chartObj, function(chart){
  self.chart = chart;
});

map.on('zoom-end', function(evt){
  self.chart.query.bbox = Cedar.extentToBbox(map.extent);
  self.chart.update();
})

```

### Cedar Impact
So, the first part of this would be to hold the mappings in the compiled chart vs actually replacing them in the template. 

The second part would be to expose the query as part of the chart, and the ability to call .update(queryParams)

### Chart Template Inputs
The inputs define the required
```
{
  "inputs": [
    {"name": "count", "type": ["numeric","string"], "required": true},
    {"name": "group", "type": ["string"], "required": false},
    {"name": "data", "type": ["url"], "required": true}
  ],
"datasources":[

 ],

...other properties...

}
```

### Compiled Chart Inputs have values stored

```
{
  "inputs": [
    {"name": "count", "type": ["numeric","string"], "required": true, "value":"ZIP_CODE"},
    {"name": "group", "type": ["string"], "required": false, "value":"TOTAL_STUD_SUM"},
    {"name": "data", "type": ["url"], "required": true, "value":"http://someservice.com/featureserver/2"}
  ],

...other properties...

}
```

**Comment by benheb** [comment]
@dbouwman @ajturner this is done right? Even with example of query being set by map extent: http://localhost:8001/examples/filter-chart-by-map-extent.html Closing.
