### ISSUE TITLE
Developer can send in arrays of values

### ISSUE THREAD

**Issue by ajturner** [esridc/cedar#31]
```javascript
var dataset = {
  "values": [
     {"height": 52},
     {"height": 103},
     {"height": 38}
   ]
}
```

**Comment by dbouwman** [comment]
Notes:
- refactor Cedar so we always pass data array to vega
- prior to the passing the array to vega, validate that the first object has the required properties specified in the mappings
- add error handlers to account for AGS sending 200's-that-are-500's and other oddities
