### ISSUE TITLE
Fix Timeline Example

### ISSUE THREAD

**Issue by dbouwman** [esridc/cedar#54]
Something happened during the refactor related to #31 that broke the timeline example

Should look like
![image](https://cloud.githubusercontent.com/assets/119129/5982785/fb71a4b8-a883-11e4-8240-f685b01e9c17.png)

but looks like
![image](https://cloud.githubusercontent.com/assets/119129/5982786/01240d6a-a884-11e4-9ee6-50205594b955.png)

**Comment by ajturner** [comment]
poke

**Comment by dbouwman** [comment]
So - the problem is that in the [time.json](https://github.com/esridc/cedar/blob/master/site/source/data/templates/time.json#L13), we were using the data[0].url property to append in an orderByField into the query.

The #31 PR changed things so that the data is always fetched by Cedar and always passed to Vega as an array. Thus, this url hack to apply a sort can't work.

Since sorting is a "first class" problem, we should have a consistent means to address it.

### Simplest Option

Allow the developer to specify a sort and attach that to the mappings. This string would be formatted exactly how the REST api expects [ordreByFields]() to be, and would simply be merged into the query string. 
```
  var dataset = {
    "url":"http://services.arcgis.com/bkrWlSKcjUDFDtgw/arcgis/rest/services/It's_a_Tornado_Map/FeatureServer/0",
    "mappings":{
      "time": {"field":"Date"},
      "value": {"field":"Injuries"},
      "sort":"Date DESC"
    }
  };
  chart.dataset = dataset;
  //or...
  chart.dataset.mappings.sort = "Date ASC";
```

This is nice because the sort could be applied to any field in the service.

### Structured Option
Add a optional `sort` property to the mappings hash. It could have values of "ASC" or "DESC" which are the values associated with [orderByFields](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Query_Feature_Service_Layer/02r3000000r1000000/) param in the REST API

```
var dataset = {
    "url":"http://services.arcgis.com/bkrWlSKcjUDFDtgw/arcgis/rest/services/It's_a_Tornado_Map/FeatureServer/0",
    "mappings":{
      "time": {"field":"Date", "sort":"ASC"},
      "value": {"field":"Injuries"}
    }
  };
```

The limitation with that is that you could only sort by one of the mapped fields. 

## Conclusion
I built out support for both, but I feel that the first is a better option. This is because with sort, the order in which the sort fields are put into the `orderByFields` string impacts the output. Putting more than one sort into the mappings, will result in non-deterministic (or at least non-obvious) ordering of the orderByFields parameter. Explicitly setting the `mappings.sort= 'FieldA ASC, FieldB DESC'` affords complete control with low "surprise" factor. PRing in a moment

**Comment by ajturner** [comment]
The first seems right to me as well.

**Comment by dbouwman** [comment]
PR for this is in #70

**Comment by benheb** [comment]
LGTM http://esridc.github.io/cedar/examples/time.html. Closing.
