### ISSUE TITLE
Clear Selection

### ISSUE THREAD

**Issue by abakirov** [esridc/cedar#69]
There is a `select` method, but there is no way to clear selection. Something like `clearSelection` method would be very useful here. As a dirty workaround, I have to call `update` and then select new items via `setTimeout(..., 200)`

**Comment by benheb** [comment]
Done.

**Comment by abakirov** [comment]
Hi,
When I call clearSelection, it will go to update which will trigger server request. This is inefficient and, more importantly, I cannot do this:
```
chart.clearSelection();
chart.select(...);
```
I still need to use setTimeout... I think clearSelection should be a synchronous operation.

What are the others' opinion on that?

**Comment by benheb** [comment]
@abakirov unless you're calling chart.update() somewhere, triggering a select/clearSelection should not trigger a server request. I also just tried calling `clearSelection();` before `select(...);` and it worked fine for me. Maybe I'm misunderstanding? 

If you watch the network tab here http://esridc.github.io/cedar/examples/map-to-chart-interaction.html you'll see it's not making any requests on select. 

Do you have a demo of this somewhere I can see?

**Comment by abakirov** [comment]
Oops, sorry, it was my code that caused server calls. Thanks for fixing this, it works perfectly!

**Comment by benheb** [comment]
:+1:
